storage: fix build error - add config dependency
bug: v/73508

During build ap_test, BLUETOOTH_SERVICE was not enabled, resulting in `service_loop.c` used by the storage module not being compiled. This caused an LD error.

/home/work/data/miui_codes/build_home_rom/out/bes_o62_ap_performance_test/../../frameworks/connectivity/bluetooth/service/common/storage_property.c:72:(.text.bt_storage_save_le_remote_device.constprop.0+0x78): undefined reference to `service_loop_work'

Signed-off-by: liuxiang18 <liuxiang18@xiaomi.com>